version: '3.9'
services:
    vue-idle-xiuxian:
        image: kowming/vue-idle-xiuxian:latest
        container_name: xiuxian
        restart: unless-stopped
        ports:
            - 8183:8080
        tty: true
        stdin_open: true