name: 创建Docker镜像

on:
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'docker user name'
        required: true
        default: ''
      docker_password:
        description: 'docker user password'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查代码
        uses: actions/checkout@v2

      - name: 登录 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_password }}

      - name: 构建Docker镜像
        run: docker build -t ${{ github.event.inputs.docker_username }}/vue-idle-xiuxian:latest .

      - name: 推送到Docker Hub
        run: docker push ${{ github.event.inputs.docker_username }}/vue-idle-xiuxian:latest


